build:
  version: "2.0"

cards:
  message: "Welcome to EasyBank Cards related prod APIs"
  contactDetails:
    name: "Utku Ince - QA Lead"
    email: "uince@easybank.com"
  onCallSupport:
    - (777) 555-1234
    - (777) 555-2345