build:
  version: "3.0"

loans:
  message: "Welcome to EasyBank Loans related local APIs"
  contactDetails:
    name: "Tutku Ince - Developer"
    email: "tince@easybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 555-2345